# Generated by Django 2.0.6 on 2018-06-11 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therulz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='rule_text',
            field=models.CharField(max_length=28),
        ),
    ]
