# Generated by Django 2.0.6 on 2018-06-13 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therulz', '0002_auto_20180610_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_name', models.CharField(max_length=50)),
                ('faq_text', models.CharField(max_length=280)),
            ],
        ),
        migrations.AlterField(
            model_name='rule',
            name='rule_text',
            field=models.CharField(max_length=280),
        ),
    ]
