# Generated by Django 2.0.6 on 2018-06-14 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therulz', '0003_auto_20180612_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
