# Generated by Django 2.0.6 on 2018-06-14 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therulz', '0004_faq_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
