# Generated by Django 2.0.6 on 2018-06-14 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therulz', '0005_auto_20180613_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player_count',
            field=models.IntegerField(default=4),
        ),
    ]
