# Generated by Django 2.0.6 on 2018-06-14 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therulz', '0006_game_player_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='player_count',
            new_name='min_player_count',
        ),
        migrations.AddField(
            model_name='game',
            name='max_player_count',
            field=models.IntegerField(default=8),
        ),
    ]
