# Generated by Django 2.0.6 on 2018-06-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therulz', '0008_auto_20180613_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='rule_order',
            field=models.IntegerField(default=0),
        ),
    ]
